### PR TITLE
Update for Hearth & Home

### PR DESCRIPTION
**Pull request by MathiasDecrock**
It seems that the code still works, it just needs to be recompiled, perhaps some signatures or defaults have changed.
Tested locally, and confirmed by another user

### CODE REVIEW

**Comment by joeyk3nobi** [comment]
so does this version work now or does it still need to be fixed?

**Comment by Kowbell** [comment]
I can confirm this too. With the most recent update (0.202.19, the first patch after H&H) just recompiling with the new dlls works.

**Comment by IlINemesisIlI** [comment]
Can someone get me a copy of the recompiled dll please? I've got no clue how to do that.

**Comment by MathiasDecrock** [comment]
@IlINemesisIlI  I uploaded a version to Discord, not sure if this will work:
https://cdn.discordapp.com/attachments/807357402332528662/888759018468806696/Build_Camera.dll

**Comment by IlINemesisIlI** [comment]
You're amazing, thank you! will try it now and report back

**Comment by Sn0wy96** [comment]
For me it Works now Thanks so much cant live without this Mod :D

**Comment by tdierickx** [comment]
THANK YOU! This is my first or second must-have mod! It's a real toss up between this one and EquipmentAndQuickSlots. 

I can confirm MathiasDecrock's file works for me. Although, I did have to rename it to "Build Camera.dll" (no underscore) to replace he one I had (I use Thunderstore Mod Manager for Valheim)

**Comment by ngynkvn** [comment]
Also recompiled the code. I can confirm the code works as is. It just needs to be rebuilt with new `assembly_valheim` and `assembly_utils` dlls.

**Comment by gittywithexcitement** [comment]
Hi everyone, thanks for helping each other out and uploading a new version while waiting for me. I updated nexus and (am updating) thunderstore with the newest version.
I'm a little paranoid about uploading someone else's DLLs, so I rebuilt it myself and that's what I've uploaded to the sites.

Thanks for your patience and have a great day.

**Comment by Omgitsbig** [comment]
Your latest updates not working, i got the recompiled dll one working. but the range you can build is set to valheim default and i cant change it higher in the config.

**Comment by gittywithexcitement** [comment]
Hi, Omgitsbig, I'm unable to reproduce what you've said "the range you can build is set to valheim default and i cant change it higher in the config". I just tested with Build Camera 1.6.1 and Valhiem 0.202.19. I built a campfire far away from the avatar and the workbench.

Please disable all other mods. I suspect you are having a mod conflict. My first suspect would be Valheim Plus, as I hear that also changes the distance you can build. Dig around in the configuration file of the offending mod, looking for a setting to change.

Also, please open new issues for new bugs. This issue was about Hearth and Home incompatibility, and that has been fixed.

**Pull request closed without merging**
